### ISSUE TITLE
Do we nned formUpdate and formCreate in cs-form?

### ISSUE THREAD

**Issue by rozner** [cloud-storm/CloudStormJS#21]
https://github.com/spicy-analytics/misto/blob/develop/rails/app/assets/javascripts/cloudstorm/components/cs-form/cs-form.js.coffee#L123

```
  return {
    restrict: 'A'
    templateUrl: 'cloudstorm/components/cs-form/cs-form-template.html'
    scope:
      csFormOptions: '='
      formResource: '=' # The resource which the form is working with
      formResourceDescriptor: '=' # The resource which the form is working with
      formItem: '=' # The resource item which the form is working with
      formMode: '@' # 'show' / 'edit' / 'create'
      createResources: '&'
      formUpdate: '=' # Callback to handle form update action (mandatory for 'edit' forms)
      formCreate: '=' # Callback to handle form create action (mandatory for 'create' forms)    
    compile: compile
  }
```
